// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtJBxaObHCJblX4GmzAUtAH_QgH25qTM',
    appId: '1:286709857353:web:855d14ddb1c7f6cea85398',
    messagingSenderId: '286709857353',
    projectId: 'fluttermock-firebase',
    authDomain: 'fluttermock-firebase.firebaseapp.com',
    storageBucket: 'fluttermock-firebase.firebasestorage.app',
    measurementId: 'G-L2NE7X8BSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkt9PwHWZly2GQazZw4R-SRzWTOS0Mgl8',
    appId: '1:286709857353:android:e8df1d5724d2bb54a85398',
    messagingSenderId: '286709857353',
    projectId: 'fluttermock-firebase',
    storageBucket: 'fluttermock-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3xYcmyfS4FNtbNsUauNQJJQHHJo3R84',
    appId: '1:286709857353:ios:842e69400946a1d4a85398',
    messagingSenderId: '286709857353',
    projectId: 'fluttermock-firebase',
    storageBucket: 'fluttermock-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3xYcmyfS4FNtbNsUauNQJJQHHJo3R84',
    appId: '1:286709857353:ios:842e69400946a1d4a85398',
    messagingSenderId: '286709857353',
    projectId: 'fluttermock-firebase',
    storageBucket: 'fluttermock-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQtJBxaObHCJblX4GmzAUtAH_QgH25qTM',
    appId: '1:286709857353:web:4e17a377a938e375a85398',
    messagingSenderId: '286709857353',
    projectId: 'fluttermock-firebase',
    authDomain: 'fluttermock-firebase.firebaseapp.com',
    storageBucket: 'fluttermock-firebase.firebasestorage.app',
    measurementId: 'G-E64D0M8CCH',
  );
}
